# modified from https://github.com/argenos/nldates-obsidian/blob/master/.github/workflows/release.yml
# which is released under MIT License

# trigger:
# modify manifest.json, package.json, versions.json
# git tag <version number>
# git push origin --tags

name: Release A New Version

on:
  push:
    tags:
      - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    environment: env-for-buildci

    env:
      DROPBOX_APP_KEY: ${{secrets.DROPBOX_APP_KEY}}
      ONEDRIVE_CLIENT_ID: ${{secrets.ONEDRIVE_CLIENT_ID}}
      ONEDRIVE_AUTHORITY: ${{secrets.ONEDRIVE_AUTHORITY}}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - name: Checkout LFS
        run: git lfs checkout
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            main.js
            manifest.json
            styles.css
          draft: false
          prerelease: false
